### ISSUE TITLE
cropping navigationBar

### ISSUE THREAD

**Issue by bizibizi** [stepanhruda/STPTransitions#13]
I use this code and then I push any VC with it I have view with offset up by navBar size

[self.navigationController pushViewController:_feedDetailVC usingTransition:transition];

**Comment by itchingpixels** [comment]
I came across this, but I believe this issue is not specific to STPTransitions, basically the Top Layout Guide doesn't get adjusted after the transition for some reason - maybe only in specific cases.

There are various workarounds:
http://stackoverflow.com/questions/20312765/navigation-controller-top-layout-guide-not-honored-with-custom-transition

**Comment by stepanhruda** [comment]
Thanks @itchingpixels. I'm gonna close this because it seems this was fixed in iOS 8.
